alias vim="nvim " 
alias esync="emerge --sync"
alias update="emerge -avDuN --with-bdeps=y @world" 
alias ek="cd /usr/src/linux" 
alias compile="make -j25 && make -j25 modules_install && make install && grub-mkconfig -o /boot/grub/grub.cfg" 
alias kcompile="make -j25 && make -j25 modules_install && make install && emerge @module-rebuild && grub-mkconfig -o /boot/grub/grub.cfg"
alias oldef="make olddefconfig" 
alias search="equery list '*' | grep " 
alias install="emerge -a " 
alias dp="emerge --depclean" 
alias e="emerge " 
alias pku="vim /etc/portage/package.use"
alias pt="cd /etc/portage"
alias mk="vim /etc/portage/make.conf"
